-- Podkategorije za Završi Mi

INSERT INTO subcategories (category_id, name, slug, sort_order) VALUES
(1, 'Renoviranje', 'renoviranje', 1),
(1, 'Popravke', 'popravke', 2),
(1, 'Instalacije', 'instalacije', 3),
(2, 'Popravka cevi', 'popravka-cevi', 1),
(2, 'Montaža sanitarija', 'montaza-sanitarija', 2),
(2, 'Grejanje', 'grejanje', 3),
(3, 'Instalacija', 'instalacija', 1),
(3, 'Popravka', 'popravka', 2),
(3, 'Revizija', 'revizija', 3),
(4, 'Farbanje', 'farbanje', 1),
(4, 'Gletovanje', 'gletovanje', 2),
(4, 'Tapetiranje', 'tapetiranje', 3),
(5, 'Pločice', 'plocice', 1),
(5, 'Fugovanje', 'fugovanje', 2),
(6, 'Košenje trave', 'kosenje-trave', 1),
(6, 'Održavanje bašte', 'odrzavanje-baste', 2),
(6, 'Sečenje drveća', 'secenje-drveca', 3),
(7, 'Selidba stana', 'selidba-stana', 1),
(7, 'Transport nameštaja', 'transport-namestaja', 2),
(8, 'Generalno čišćenje', 'generalno-ciscenje', 1),
(8, 'Deep cleaning', 'deep-cleaning', 2),
(9, 'Čuvanje po satu', 'cuvanje-po-satu', 1),
(9, 'Čuvanje preko noći', 'cuvanje-preko-noci', 2),
(10, 'Šetanje pasa', 'setanje-pasa', 1),
(10, 'Čuvanje na adresi', 'cuvanje-na-adresi', 2),
(11, 'Popravka računara', 'popravka-racunara', 1),
(11, 'Mreže i WiFi', 'mreze-wifi', 2),
(11, 'Web sajtovi', 'web-sajtovi', 3),
(12, 'Matematika', 'matematika', 1),
(12, 'Jezici', 'jezici', 2),
(12, 'Muzika', 'muzika', 3);
